INSERT INTO USERS (USER_ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, NAME, PASSWORD, PRIMARY_EMAIL)
VALUES (1, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, 'Jill', '$2a$10$UQv7DHutyDHasewr4tiSgeGz2hZtc/jmJzE2UN2bctI9U9s45BQZS', 'jill@anaddress.com'),
VALUES (2, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, 'Jack', '$2a$10$UQv7DHutyDHasewr4tiSgeGz2hZtc/jmJzE2UN2bctI9U9s45BQZS', 'jack@anaddress.com'),
VALUES (3, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, 'Tom', '$2a$10$UQv7DHutyDHasewr4tiSgeGz2hZtc/jmJzE2UN2bctI9U9s45BQZS', 'tom@anaddress.com');

INSERT INTO ROLES (ROLE_ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, NAME)
VALUES ( 1, CURRENT_USER ,CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, 'ADMIN'),
VALUES ( 2, CURRENT_USER ,CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, 'USER'),
VALUES ( 3, CURRENT_USER ,CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, 'DATA');


INSERT INTO USER_ROLES (ROLE_ID, USER_ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
VALUES ( 1, 1, CURRENT_USER ,CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP),
VALUES ( 1, 2, CURRENT_USER ,CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP),
VALUES ( 2, 2, CURRENT_USER ,CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP),
VALUES ( 2, 3, CURRENT_USER ,CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP);

