INSERT INTO USERS (USER_ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, NAME, PASSWORD, PRIMARY_EMAIL) VALUES (1, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, 'Jill', '$2a$10$UQv7DHutyDHasewr4tiSgeGz2hZtc/jmJzE2UN2bctI9U9s45BQZS', 'jill@anaddress.com');
INSERT INTO USERS (USER_ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, NAME, PASSWORD, PRIMARY_EMAIL) VALUES (2, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP, 'Jack', '$2a$10$UQv7DHutyDHasewr4tiSgeGz2hZtc/jmJzE2UN2bctI9U9s45BQZS', 'jack@anaddress.com');

