package com.lambdaschool.marketplace.models;

import javax.persistence.*;

/**
 * The entity allowing interaction with the categories table
 */
@Entity
@Table(name = "marketplaces")
public class Marketplace extends Auditable {
  /**
   * The primary key (long) of the items table.
   */
  @Id
  @GeneratedValue
  private long marketplaceId;

  /**
   * Item name. Cannot be null.
   */
  @Column(nullable = false)
  private String name;

  /**
   * Default constructor used primarily by the JPA.
   */
  public Marketplace() {}

  /**
   * Give the params, create a new marketplace object.
   * marketplaceId is autogenerated
   *
   * @param name The name (String) of the marketplace
   */
  public Marketplace(String name) {
    this.name = name;
  }

  /**
   * Getter for marketplaceId
   *
   * @return the marketplaceId (long) of the marketplace
   */
  public long getMarketplaceId() {
    return marketplaceId;
  }

  /**
   * Setter for marketplaceId. Used primary for seeding data
   *
   * @param marketplaceId the new marketplaceId (long) of the marketplace
   */
  public void setMarketplaceId(long marketplaceId) {
    this.marketplaceId = marketplaceId;
  }

  /**
   * Getter for name
   *
   * @return the name (String) of the marketplace
   */
  public String getName() {
    return name;
  }

  /**
   * Setter for item name
   *
   * @param name (string) of the marketplace
   */
  public void setName(String name) {
    this.name = name;
  }
}
