package com.lambdaschool.marketplace.models;

import javax.persistence.*;

/**
 * The entity allowing interaction with the categories table
 */
@Entity
@Table(name = "products")
public class Product extends Auditable {
  /**
   * The primary key (long) of the items table.
   */
  @Id
  @GeneratedValue
  private long productId;

  /**
   * Item name. Cannot be null.
   */
  @Column(nullable = false)
  private String name;

  /**
   * Default constructor used primarily by the JPA.
   */
  public Product() {}

  /**
   * Give the params, create a new product object.
   * productId is autogenerated
   *
   * @param name The name (String) of the product
   */
  public Product(String name) {
    this.name = name;
  }

  /**
   * Getter for productId
   *
   * @return the productId (long) of the product
   */
  public long getProductId() {
    return productId;
  }

  /**
   * Setter for productId. Used primary for seeding data
   *
   * @param productId the new productId (long) of the product
   */
  public void setProductId(long productId) {
    this.productId = productId;
  }

  /**
   * Getter for name
   *
   * @return the name (String) of the product
   */
  public String getName() {
    return name;
  }

  /**
   * Setter for item name
   *
   * @param name (string) of the product
   */
  public void setName(String name) {
    this.name = name;
  }
}
